import "./globals.css";
import Nav from "./components/nav";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body className="mx-64">
        <Nav user={session?.user} expires={session?.expires} />
        {children}
      </body>
    </html>
  );
}
